from src.scrapers import (
    scrape_brevete,
    scrape_revtec,
    scrape_sutran,
    scrape_satimp,
    scrape_recvehic,
    scrape_sunarp,
    scrape_satmul,
    scrape_soat,
    scrape_calmul,
    scrape_maqmant,
)


def config(indice):
    return {
        "DataMtcRecordsConductores": {
            "api": False,
            "residential_proxy": False,
            "indice_placa": False,
            "funcion_scraper": scrape_recvehic,
            "timeout": 90,
            "estructura_respuesta": {
                "ImageBytes": 0,
            },
            "campo_fecha_hasta": "",
        },
        "DataMtcBrevetes": {
            "api": False,
            "residential_proxy": True,
            "indice_placa": False,
            "funcion_scraper": scrape_brevete,
            "timeout": 90,
            "estructura_respuesta": {
                "Clase": 0,
                "Numero": 1,
                "Tipo": 2,
                "FechaExp": 3,
                "Restricciones": 4,
                "FechaHasta": 5,
                "Centro": 6,
                "Puntos": 7,
                "Record": 8,
            },
            "campo_fecha_hasta": "FechaHasta",
            "alerta_dias": "-45, -25, -5, 0, 1, 2, 3",
        },
        "DataSatMultas": {
            "api": False,
            "residential_proxy": False,
            "indice_placa": True,
            "funcion_scraper": scrape_satmul,
            "timeout": 300,
            "estructura_respuesta": {
                "IdPlaca_FK": None,
                "PlacaValidate": 0,
                "Reglamento": 1,
                "Falta": 2,
                "Documento": 3,
                "FechaEmision": 4,
                "Importe": 5,
                "Gastos": 6,
                "Descuento": 7,
                "Deuda": 8,
                "Estado": 9,
                "Licencia": 10,
                "DocTipoSatmul": 11,
                "DocNumSatmul": 12,
                "ImageBytes1": 13,
                "ImageBytes2": 14,
            },
            "campo_fecha_hasta": "",
        },
        "DataSatImpuestos": {
            "api": False,
            "residential_proxy": False,
            "indice_placa": False,
            "funcion_scraper": scrape_satimp,
            "timeout": 90,
            "estructura_respuesta": {
                "Codigo": 0,
                "Ano": 1,
                "Periodo": 2,
                "DocNum": 3,
                "TotalAPagar": 4,
                "FechaHasta": 5,
            },
            "campo_fecha_hasta": "FechaHasta",
            "alerta_dias": "-10, -5, -1, 0, 1, 2, 3",
        },
        "DataMtcRevisionesTecnicas": {
            "api": False,
            "residential_proxy": True,
            "indice_placa": True,
            "funcion_scraper": scrape_revtec,
            "timeout": 90,
            "estructura_respuesta": {
                "IdPlaca_FK": None,
                "Certificadora": 0,
                "PlacaValidate": 2,
                "Certificado": 3,
                "FechaDesde": 4,
                "FechaHasta": 5,
                "Resultado": 6,
                "Vigencia": 7,
            },
            "campo_fecha_hasta": "FechaHasta",
            "alerta_dias": "-25, -15, -5, 0, 1, 2, 3",
        },
        "DataSutranMultas": {
            "api": False,
            "residential_proxy": False,
            "indice_placa": True,
            "funcion_scraper": scrape_sutran,
            "timeout": 90,
            "estructura_respuesta": {
                "Documento": 0,
                "Tipo": 1,
                "FechaDoc": 2,
                "CodigoInfrac": 3,
                "Clasificacion": 4,
            },
            "campo_fecha_hasta": "",
        },
        "DataSunarpFichas": {
            "api": False,
            "residential_proxy": True,
            "indice_placa": True,
            "funcion_scraper": scrape_sunarp,
            "timeout": 90,
        },
        "DataApesegSoats": {
            "api": False,
            "residential_proxy": False,
            "indice_placa": True,
            "funcion_scraper": scrape_soat,
            "timeout": 90,
            "estructura_respuesta": {
                "IdPlaca_FK": None,
                "Aseguradora": 0,
                "Vigencia": 1,
                "FechaInicio": 2,
                "FechaHasta": 3,
                "PlacaValidate": 4,
                "Certificado": 5,
                "Uso": 6,
                "Clase": 7,
                "Tipo": 8,
                "FechaVenta": 9,
                "ImageBytes": None,
            },
            "campo_fecha_hasta": "",
            "alerta_dias": "-10, -5, -1, 0, 1, 2, 3",
        },
        "DataCallaoMultas": {
            "api": False,
            "residential_proxy": False,
            "indice_placa": True,
            "funcion_scraper": scrape_calmul,
            "timeout": 60,
            "estructura_respuesta": {
                "PlacaValidate": 0,
                "Codigo": 1,
                "NumeroPapeleta": 2,
                "FechaInfraccion": 3,
                "TotalInfraccion": 4,
                "TotalBeneficio": 5,
                "ImageBytes": None,
            },
            "campo_fecha_hasta": "",
        },
        "DataMaquinariasMantenimiento": {
            "api": True,
            "residential_proxy": False,
            "indice_placa": True,
            "funcion_scraper": scrape_maqmant,
            "timeout": 15,
            "estructura_respuesta": {
                "FechaUltimoServicio": 0,
                "UltimoServicioDetalle": 1,
                "FechaProximoServicio": 2,
                "ProximoServicioDetalle": 3,
            },
            "campo_fecha_hasta": "FechaProximoServicio",
            "alerta_dias": "-10, -5, -1, 0, 1, 2, 3",
        },
    }[indice]
