from datetime import datetime as dt
from copy import deepcopy as copy
from src.utils.constants import GATHER_ITERATIONS
from src.updates import (
    scrape_brevete,
    scrape_revtec,
    scrape_sutran,
    scrape_satimp,
    scrape_recvehic,
    scrape_sunarp,
    scrape_satmul,
    scrape_soat,
)
from src.utils.utils import create_soat_certificate

SCRAPER_CONFIGS = {
    "recvehic": {
        "headless_key": "revtec",
        "scraper": scrape_recvehic,
        "update_key": "DataMtcRecordsConductores",
        "is_member_data": True,
        "response_handler": lambda item, response, id_member: {
            "IdMember_FK": id_member,
            "ImageBytes": response,
            "LastUpdate": dt.now().strftime("%Y-%m-%d"),
        },
    },
    "brevetes": {
        "headless_key": "brevetes",
        "scraper": scrape_brevete,
        "update_key": "DataMtcBrevetes",
        "is_member_data": True,
        "response_handler": lambda item, response, id_member: {
            "IdMember_FK": id_member,
            "Clase": response[0],
            "Numero": response[1],
            "Tipo": response[2],
            "FechaExp": response[3],
            "Restricciones": response[4],
            "FechaHasta": response[5],
            "Centro": response[6],
            "Puntos": response[7],
            "Record": response[8],
            "LastUpdate": dt.now().strftime("%Y-%m-%d"),
        },
    },
    "satmuls": {
        "headless_key": "satmul",
        "scraper": scrape_satmul,
        "update_key": "DataSatMultas",
        "is_member_data": False,
        "iterations": GATHER_ITERATIONS * 2,
        "response_handler": lambda item, response_list, placa: [
            {
                "IdPlaca_FK": 999,
                "PlacaValidate": n[0],
                "Reglamento": n[1],
                "Falta": n[2],
                "Documento": n[3],
                "FechaEmision": n[4],
                "Importe": n[5],
                "Gastos": n[6],
                "Descuento": n[7],
                "Deuda": n[8],
                "Estado": n[9],
                "Licencia": n[10],
                "DocTipoSatmul": n[11],
                "DocNumSatmul": n[12],
                "ImageBytes1": n[13],
                "ImageBytes2": n[14] if len(n) > 14 else "",
                "LastUpdate": dt.now().strftime("%Y-%m-%d"),
            }
            for n in response_list
        ],
    },
    "revtecs": {
        "headless_key": "revtec",
        "scraper": scrape_revtec,
        "update_key": "DataMtcRevisionesTecnicas",
        "is_member_data": False,
        "response_handler": lambda item, response, placa: {
            "IdPlaca_FK": 999,
            "Certificadora": response[0],
            "PlacaValidate": response[2],
            "Certificado": response[3],
            "FechaDesde": response[4],
            "FechaHasta": response[5],
            "Resultado": response[6],
            "Vigencia": response[7],
            "LastUpdate": dt.now().strftime("%Y-%m-%d"),
        },
    },
    "sutrans": {
        "headless_key": "revtec",
        "scraper": scrape_sutran,
        "update_key": "DataSutranMultas",
        "is_member_data": False,
        "response_handler": lambda item, response_list, placa: [
            {
                "PlacaValidate": placa,
                "Documento": n[0],
                "Tipo": n[1],
                "FechaDoc": n[2],
                "CodigoInfrac": n[3],
                "Clasificacion": n[4],
                "LastUpdate": dt.now().strftime("%Y-%m-%d"),
            }
            for n in response_list
        ],
    },
    "satimps": {
        "headless_key": "revtec",
        "scraper": scrape_satimp,
        "update_key": "DataSatImpuestos",
        "is_member_data": True,
        "response_handler": None,
    },
    "sunarps": {
        "headless_key": "sunarp",
        "scraper": scrape_sunarp,
        "update_key": "DataSunarpFichas",
        "is_member_data": False,
        "response_handler": lambda item, response, placa: {
            "IdPlaca_FK": 999,
            "PlacaValidate": placa,
            "ImageBytes": response,
            "LastUpdate": dt.now().strftime("%Y-%m-%d"),
            "Serie": "",
            "VIN": "",
            "Motor": "",
            "Color": "",
            "Marca": "",
            "Modelo": "",
            "Ano": "",
            "PlacaVigente": "",
            "PlacaAnterior": "",
            "Estado": "",
            "Anotaciones": "",
            "Sede": "",
            "Propietarios": "",
        },
        "skip_response_if_captcha": True,
    },
    "soats": {
        "headless_key": "soat",
        "scraper": scrape_soat,
        "update_key": "DataApesegSoats",
        "is_member_data": False,
        "response_handler": lambda item, response, placa: {
            "IdPlaca_FK": 999,
            "Aseguradora": response[0],
            "FechaInicio": response[2],
            "FechaHasta": response[3],
            "PlacaValidate": response[4],
            "Certificado": response[5],
            "Uso": response[6],
            "Clase": response[7],
            "Vigencia": response[1],
            "Tipo": response[8],
            "FechaVenta": response[9],
            "ImageBytes": create_soat_certificate(data=copy(response)),
            "LastUpdate": dt.now().strftime("%Y-%m-%d"),
        },
    },
}
